MONTAGE_TCP_LE = [('EEG FP1-LE', 'EEG F7-LE'),
	 ('EEG F7-LE', 'EEG T3-LE'),
	 ('EEG T3-LE', 'EEG T5-LE'),
	 ('EEG T5-LE', 'EEG O1-LE'),
	 ('EEG FP2-LE', 'EEG F8-LE'),
	 ('EEG F8-LE', 'EEG T4-LE'),
	 ('EEG T4-LE', 'EEG T6-LE'),
	 ('EEG T6-LE', 'EEG O2-LE'),
	 # ('EEG A1-LE', 'EEG T3-LE'),
	 ('EEG T3-LE', 'EEG C3-LE'),
	 ('EEG C3-LE', 'EEG CZ-LE'),
	 ('EEG CZ-LE', 'EEG C4-LE'),
	 ('EEG C4-LE', 'EEG T4-LE'),
	 # ('EEG T4-LE', 'EEG A2-LE'),
	 ('EEG FP1-LE', 'EEG F3-LE'),
	 ('EEG F3-LE', 'EEG C3-LE'),
	 ('EEG C3-LE', 'EEG P3-LE'),
	 ('EEG P3-LE', 'EEG O1-LE'),
	 ('EEG FP2-LE', 'EEG F4-LE'),
	 ('EEG F4-LE', 'EEG C4-LE'),
	 ('EEG C4-LE', 'EEG P4-LE'),
	 ('EEG P4-LE', 'EEG O2-LE')] #,
	 # ('EEG EKG-LE',)]

MONTAGE_TCP_AR = [('EEG FP1-REF', 'EEG F7-REF'),
	 ('EEG F7-REF', 'EEG T3-REF'),
	 ('EEG T3-REF', 'EEG T5-REF'),
	 ('EEG T5-REF', 'EEG O1-REF'),
	 ('EEG FP2-REF', 'EEG F8-REF'),
	 ('EEG F8-REF', 'EEG T4-REF'),
	 ('EEG T4-REF', 'EEG T6-REF'),
	 ('EEG T6-REF', 'EEG O2-REF'),
	 # ('EEG A1-REF', 'EEG T3-REF'),
	 ('EEG T3-REF', 'EEG C3-REF'),
	 ('EEG C3-REF', 'EEG CZ-REF'),
	 ('EEG CZ-REF', 'EEG C4-REF'),
	 ('EEG C4-REF', 'EEG T4-REF'),
	 # ('EEG T4-REF', 'EEG A2-REF'),
	 ('EEG FP1-REF', 'EEG F3-REF'),
	 ('EEG F3-REF', 'EEG C3-REF'),
	 ('EEG C3-REF', 'EEG P3-REF'),
	 ('EEG P3-REF', 'EEG O1-REF'),
	 ('EEG FP2-REF', 'EEG F4-REF'),
	 ('EEG F4-REF', 'EEG C4-REF'),
	 ('EEG C4-REF', 'EEG P4-REF'),
	 ('EEG P4-REF', 'EEG O2-REF')]

MONTAGE_TCP_AR_A = [('EEG FP1-REF', 'EEG F7-REF'),
	 ('EEG F7-REF', 'EEG T3-REF'),
	 ('EEG T3-REF', 'EEG T5-REF'),
	 ('EEG T5-REF', 'EEG O1-REF'),
	 ('EEG FP2-REF', 'EEG F8-REF'),
	 ('EEG F8-REF', 'EEG T4-REF'),
	 ('EEG T4-REF', 'EEG T6-REF'),
	 ('EEG T6-REF', 'EEG O2-REF'),
	 ('EEG T3-REF', 'EEG C3-REF'),
	 ('EEG C3-REF', 'EEG CZ-REF'),
	 ('EEG CZ-REF', 'EEG C4-REF'),
	 ('EEG C4-REF', 'EEG T4-REF'),
	 ('EEG FP1-REF', 'EEG F3-REF'),
	 ('EEG F3-REF', 'EEG C3-REF'),
	 ('EEG C3-REF', 'EEG P3-REF'),
	 ('EEG P3-REF', 'EEG O1-REF'),
	 ('EEG FP2-REF', 'EEG F4-REF'),
	 ('EEG F4-REF', 'EEG C4-REF'),
	 ('EEG C4-REF', 'EEG P4-REF'),
	 ('EEG P4-REF', 'EEG O2-REF')]

MONTAGE_TCP_LE_A = [('EEG FP1-LE', 'EEG F7-LE'),
	 ('EEG F7-LE', 'EEG T3-LE'),
	 ('EEG T3-LE', 'EEG T5-LE'),
	 ('EEG T5-LE', 'EEG O1-LE'),
	 ('EEG FP2-LE', 'EEG F8-LE'),
	 ('EEG F8-LE', 'EEG T4-LE'),
	 ('EEG T4-LE', 'EEG T6-LE'),
	 ('EEG T6-LE', 'EEG O2-LE'),
	 ('EEG T3-LE', 'EEG C3-LE'),
	 ('EEG C3-LE', 'EEG CZ-LE'),
	 ('EEG CZ-LE', 'EEG C4-LE'),
	 ('EEG C4-LE', 'EEG T4-LE'),
	 ('EEG FP1-LE', 'EEG F3-LE'),
	 ('EEG F3-LE', 'EEG C3-LE'),
	 ('EEG C3-LE', 'EEG P3-LE'),
	 ('EEG P3-LE', 'EEG O1-LE'),
	 ('EEG FP2-LE', 'EEG F4-LE'),
	 ('EEG F4-LE', 'EEG C4-LE'),
	 ('EEG C4-LE', 'EEG P4-LE'),
	 ('EEG P4-LE', 'EEG O2-LE')]